"""
simulate_poisoning_attack.py

Simulates a "boiling the frog" adversarial baseline-poisoning attack
against a continuously-adapting behavioral biometric baseline, and
compares the attacker's success rate under:

  (A) a naive continuously-adapting baseline (EMA on every sample), vs
  (B) the Asymmetric Learning Gate (ALG) defense in this repo.

Threat scenario
---------------
An attacker has obtained a live, authenticated session on the victim's
device (e.g. via a stolen DPoP-bound token used from a malware-controlled
process, or session hijack). The attacker cannot forge hardware-backed
FIDO2/WebAuthn assertions (that requires physical possession of the
authenticator + user presence), so high-assurance anchor events in this
simulation are modeled as only ever reflecting the real victim's true
behavior. The attacker CAN inject arbitrary continuous telemetry
(keystroke/mouse timing) between those anchor events, and attempts to
slowly shift that injected telemetry away from the victim baseline and
toward their own natural behavior, hoping the system's trust score will
eventually accept their own behavior outright.

We measure: over time, what fraction of the attacker's own (fixed,
unshifted) behavior samples would be ACCEPTED (trust_score below the
authentication threshold) by each baseline regime.

This is a synthetic simulation with simulated data; the numbers below
are not claims about any real deployed system, but they are real
outputs of the code in this repository, generated by actually running
it (see README.md in this folder for the captured run).
"""

from __future__ import annotations

import numpy as np

from asymmetric_learning_gate import AsymmetricLearningGate, NaiveContinuousBaseline

RNG = np.random.default_rng(42)

# ---------------------------------------------------------------------
# Simulation parameters
# ---------------------------------------------------------------------
VICTIM_MEAN = 180.0   # e.g. mean inter-keystroke interval in ms
VICTIM_STD = 18.0
ATTACKER_MEAN = 260.0  # attacker's natural typing rhythm, clearly different
ATTACKER_STD = 22.0

TRUST_THRESHOLD_Z = 2.0  # accept if |z| < threshold

N_ANCHOR_EVENTS = 40          # total high-assurance (victim-only) events over the sim
SAMPLES_PER_ANCHOR = 15       # telemetry samples right after each anchor event
CONTINUOUS_SAMPLES_PER_ROUND = 40  # attacker-injected ambient samples between anchors

ATTACK_START_ROUND = 5         # attacker begins drifting after this many rounds
DRIFT_STEP = 4.0                # ms the attacker shifts their injected mean per round
DRIFT_CAP_ROUNDS = 30            # rounds over which the full drift ramps in


def victim_sample(n=1):
    return RNG.normal(VICTIM_MEAN, VICTIM_STD, size=n)


def attacker_injected_sample(round_idx: int, n=1):
    """Attacker-controlled continuous telemetry: starts at the victim's
    mean (to blend in) and ramps toward the attacker's own mean."""
    if round_idx < ATTACK_START_ROUND:
        target_shift = 0.0
    else:
        progress = min(1.0, (round_idx - ATTACK_START_ROUND) / DRIFT_CAP_ROUNDS)
        target_shift = progress * (ATTACKER_MEAN - VICTIM_MEAN)
    shifted_mean = VICTIM_MEAN + target_shift
    # Attacker injects with low noise to look "consistent"/confident.
    return RNG.normal(shifted_mean, VICTIM_STD * 0.7, size=n)


def attacker_true_sample(n=1):
    """The attacker's actual, unshifted natural behavior -- what we
    measure acceptance of as the real attack goal."""
    return RNG.normal(ATTACKER_MEAN, ATTACKER_STD, size=n)


def run_simulation():
    naive = NaiveContinuousBaseline(VICTIM_MEAN, VICTIM_STD)
    alg = AsymmetricLearningGate(VICTIM_MEAN, VICTIM_STD)

    rows = []
    for round_idx in range(N_ANCHOR_EVENTS):
        # 1. High-assurance anchor event: only the TRUE victim can produce
        #    this (hardware-backed), so it's always drawn from the victim
        #    distribution in both regimes.
        anchor_batch = victim_sample(SAMPLES_PER_ANCHOR)
        naive_anchor_event_label = "anchor"  # naive baseline doesn't distinguish anyway
        for s in anchor_batch:
            naive.observe(s)  # naive: anchor samples ALSO just get folded in as-is
        alg_result = alg.submit_anchor_batch(anchor_batch)

        # 2. Ambient/continuous telemetry: attacker-controlled & possibly
        #    drifting. Naive baseline folds every one of these in too.
        continuous_batch = attacker_injected_sample(round_idx, CONTINUOUS_SAMPLES_PER_ROUND)
        for s in continuous_batch:
            naive.observe(s)
        # ALG: continuous telemetry NEVER updates the baseline -- it's
        # intentionally not even passed to alg.submit_anchor_batch.

        # 3. Measure: would the attacker's TRUE behavior be accepted right now?
        attacker_probe = attacker_true_sample(200)
        naive_accept_rate = float(np.mean([naive.trust_score(x) < TRUST_THRESHOLD_Z for x in attacker_probe]))
        alg_accept_rate = float(np.mean([alg.trust_score(x) < TRUST_THRESHOLD_Z for x in attacker_probe]))

        # Also track legitimate-victim usability (false-reject risk) under each regime.
        victim_probe = victim_sample(200)
        naive_victim_accept = float(np.mean([naive.trust_score(x) < TRUST_THRESHOLD_Z for x in victim_probe]))
        alg_victim_accept = float(np.mean([alg.trust_score(x) < TRUST_THRESHOLD_Z for x in victim_probe]))

        rows.append(dict(
            round=round_idx,
            naive_mean=naive.mean, naive_std=naive.std,
            alg_mean=alg.mean, alg_std=alg.std,
            alg_gate_result=alg_result,
            naive_attacker_accept=naive_accept_rate,
            alg_attacker_accept=alg_accept_rate,
            naive_victim_accept=naive_victim_accept,
            alg_victim_accept=alg_victim_accept,
        ))

    return rows, alg


def main():
    rows, alg = run_simulation()

    print(f"{'rnd':>3} {'naive_mu':>9} {'alg_mu':>8} {'gate':>11} "
          f"{'naive_atk%':>11} {'alg_atk%':>9} {'naive_vic%':>11} {'alg_vic%':>9}")
    for r in rows:
        print(f"{r['round']:>3} {r['naive_mean']:>9.2f} {r['alg_mean']:>8.2f} "
              f"{r['alg_gate_result']:>11} "
              f"{r['naive_attacker_accept']*100:>10.1f}% {r['alg_attacker_accept']*100:>8.1f}% "
              f"{r['naive_victim_accept']*100:>10.1f}% {r['alg_victim_accept']*100:>8.1f}%")

    final = rows[-1]
    early_window = rows[:ATTACK_START_ROUND]
    late_window = rows[-5:]

    print("\n=== Summary ===")
    print(f"Victim true mean: {VICTIM_MEAN}, Attacker true mean: {ATTACKER_MEAN}")
    print(f"Naive baseline drifted from {VICTIM_MEAN:.2f} -> {final['naive_mean']:.2f} "
          f"(moved {abs(final['naive_mean']-VICTIM_MEAN):.2f} of {abs(ATTACKER_MEAN-VICTIM_MEAN):.2f} possible ms)")
    print(f"ALG baseline drifted from {VICTIM_MEAN:.2f} -> {final['alg_mean']:.2f} "
          f"(moved {abs(final['alg_mean']-VICTIM_MEAN):.2f} of {abs(ATTACKER_MEAN-VICTIM_MEAN):.2f} possible ms)")

    avg_naive_attacker_late = np.mean([r['naive_attacker_accept'] for r in late_window]) * 100
    avg_alg_attacker_late = np.mean([r['alg_attacker_accept'] for r in late_window]) * 100
    avg_naive_victim_late = np.mean([r['naive_victim_accept'] for r in late_window]) * 100
    avg_alg_victim_late = np.mean([r['alg_victim_accept'] for r in late_window]) * 100

    print(f"\nFinal-5-rounds avg attacker acceptance rate: naive={avg_naive_attacker_late:.1f}% "
          f"vs ALG={avg_alg_attacker_late:.1f}%")
    print(f"Final-5-rounds avg legitimate-victim acceptance rate (usability): "
          f"naive={avg_naive_victim_late:.1f}% vs ALG={avg_alg_victim_late:.1f}%")
    print(f"\nALG internal stats: merges={alg.merges}, rejected_batches={alg.rejected_batches}, "
          f"drift_resets={alg.drift_resets}")


if __name__ == "__main__":
    main()
